version: '2'
services:
    jhipsteroauth2sampleapplication-app:
        image: jhipsteroauth2sampleapplication
        external_links:
            - jhipsteroauth2sampleapplication-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipsteroauth2sampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    jhipsteroauth2sampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsteroauth2sampleapplication-mysql
